# Generated by Django 3.0.3 on 2020-02-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.TextField(max_length=200)),
                ('orgaddr', models.TextField(max_length=2000)),
                ('orgpra', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('phone', models.TextField(max_length=15)),
                ('orgid', models.ForeignKey(default='3333', on_delete=django.db.models.deletion.SET_DEFAULT, to='myweb.Org')),
            ],
        ),
    ]
