# Generated by Django 3.0.3 on 2020-02-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactor',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='contactor',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='org',
            name='orgaddr',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='org',
            name='orgname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='org',
            name='orgpra',
            field=models.CharField(max_length=200),
        ),
    ]
