# Generated by Django 3.0.3 on 2020-02-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_auto_20200214_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logtime', models.DateTimeField(auto_now_add=True)),
                ('logcontent', models.TextField(max_length=2000)),
            ],
        ),
    ]
