# Generated by Django 3.0.3 on 2020-02-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_elog'),
    ]

    operations = [
        migrations.AddField(
            model_name='elog',
            name='slug',
            field=models.SlugField(default='This is slug', unique=True),
        ),
    ]
